---
- hosts: picluster
  tasks:
  - name: "enable overlay"
    lineinfile: dest=/etc/modules line="overlay"
  - name: Execute REBOOT
    shell: shutdown -r -t 5 
  - name: rebooting... wait for host
    local_action: wait_for host={{ ansible_hostname }} state=started delay=60 timeout=300 connect_timeout=15 port=22
  - name: Install Docker
    shell: "curl -sSL https://get.docker.com | sh"
  - name: enable pi as docker user
    shell: usermod -aG docker pi
  - name: "configure docker remote"
    lineinfile: dest=/etc/systemd/system/docker.service.d/overlay.conf regexp="^ExecStart=/usr/bin/dockerd" line="ExecStart=/usr/bin/dockerd --storage-driver overlay -H fd:// -H tcp://0.0.0.0:2375"
    notify:
     - reload systemd
     - restart docker
  - name: Install dependencies
    apt:
      name={{ item }}
      update_cache=yes
    with_items:
      - ntp
      - python-dev
      - python-setuptools

  - name: Install pip
    easy_install:
      name=pip

  - name: Install docker-py
    pip:
      name=docker-py
      state=present
      version=1.7.0
  handlers:
  - name: reload systemd
    command: systemctl daemon-reload
  - name: restart docker
    command: systemctl restart docker.service
