---
- hosts: picluster
  vars:
   KERNEL_SRC: /root/raspbian-kernel/kernel.tar.gz
   KERNEL_DEST: /home/pi/kernel.tar.gz
  tasks:
  - name: "copy kernel.tar.gz"
    copy: src="{{ KERNEL_SRC }}" dest="{{ KERNEL_DEST }}"
  - name: "deflate and install kernel"
    shell: "{{ item }}" 
    with_items:
     - "tar --no-same-owner -xvzf {{ KERNEL_DEST }} -C /"
     - cp /boot/config.txt /boot/config.txt-'date +%Y%m%k-%I%M%S'
     - grep -q '^kernel=.*' /boot/config.txt && sed -i 's/^kernel=.*/kernel=kernel-custom.img/m' /boot/config.txt || echo 'kernel=kernel-custom.img' >> /boot/config.txt
  - name: "enable rbd support in /etc/modules"
    lineinfile: dest=/etc/modules line='rbd'
  - name: "update-initramfs"
    shell: update-initramfs -u
  - name: Execute REBOOT
    shell: shutdown -r -t 2
  - name: rebooting... wait for host
    local_action: wait_for host={{ ansible_hostname }} state=started delay=60 timeout=300 connect_timeout=15 port=22
  
